name: /YOUR_PATH/conda_envs/collusive_agent
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cuda-nvcc=12.1.105=0
  - expat=2.7.3=h3385a95_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl_fft=2.1.1=py310h8fe796d_0
  - mkl_random=1.3.0=py310h505adc9_0
  - ncurses=6.5=h7934f7d_0
  - numpy-base=1.26.4=py310he1678cf_1
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - accelerate==0.34.0
    - annotated-doc==0.0.4
    - anthropic==0.71.0
    - apache-tvm-ffi==0.1.6
    - astor==0.8.1
    - attrs==25.4.0
    - bitsandbytes==0.44.0
    - blake3==1.0.8
    - cachetools==6.2.4
    - cbor2==5.7.1
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloudpickle==3.1.2
    - compressed-tensors==0.12.2
    - contourpy==1.3.2
    - cryptography==46.0.3
    - cuda-bindings==13.1.1
    - cuda-pathfinder==1.3.3
    - cuda-python==13.1.1
    - cupy-cuda12x==13.6.0
    - cycler==0.12.1
    - depyf==0.20.0
    - diskcache==5.6.3
    - dnspython==2.8.0
    - docstring-parser==0.17.0
    - einops==0.8.1
    - email-validator==2.3.0
    - fastapi==0.127.0
    - fastapi-cli==0.0.20
    - fastapi-cloud-cli==0.8.0
    - fastar==0.8.0
    - fastrlock==0.8.3
    - filelock==3.20.1
    - flash-attn==2.8.3
    - flashinfer-python==0.5.3
    - fonttools==4.61.1
    - gguf==0.10.0
    - hf-xet==1.2.0
    - httptools==0.7.1
    - httpx-sse==0.4.3
    - huggingface-hub==0.36.0
    - ijson==3.4.0.post0
    - importlib-metadata==8.7.1
    - interegular==0.3.3
    - jinja2==3.1.6
    - jiter==0.12.0
    - jmespath==1.0.1
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - kiwisolver==1.4.9
    - lark==1.2.2
    - llguidance==1.3.0
    - llvmlite==0.44.0
    - lm-format-enforcer==0.10.6
    - loguru==0.7.3
    - markdown-it-py==4.0.0
    - markupsafe==2.1.5
    - matplotlib==3.10.8
    - mcp==1.25.0
    - mdurl==0.1.2
    - mistral-common==1.8.8
    - mkl-fft==2.1.1
    - mkl-random==1.3.0
    - mkl-service==2.5.2
    - model-hosting-container-standards==0.1.12
    - msgpack==1.1.2
    - msgspec==0.20.0
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - ninja==1.13.0
    - numba==0.61.2
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cudnn-frontend==1.17.0
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-cutlass-dsl==4.3.4
    - nvidia-ml-py==13.590.44
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.1.105
    - openai==2.8.1
    - openai-harmony==0.0.8
    - opencv-python-headless==4.11.0.86
    - outlines==0.0.46
    - outlines-core==0.2.11
    - packaging==25.0
    - pandas==2.3.3
    - partial-json-parser==0.2.1.1.post7
    - pillow==12.0.0
    - prometheus-client==0.23.1
    - prometheus-fastapi-instrumentator==7.1.0
    - protobuf==6.33.2
    - psutil==7.2.0
    - py-cpuinfo==9.0.0
    - pyairports==0.0.1
    - pybase64==1.4.3
    - pycountry==24.6.1
    - pycparser==2.23
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pydantic-extra-types==2.10.6
    - pydantic-settings==2.12.0
    - pygments==2.19.2
    - pyjwt==2.10.1
    - pyparsing==3.3.1
    - pytesseract==0.3.13
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - python-json-logger==4.0.0
    - python-multipart==0.0.21
    - pytz==2025.2
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - ray==2.53.0
    - referencing==0.37.0
    - requests==2.32.5
    - rich==14.2.0
    - rich-toolkit==0.17.1
    - rignore==0.7.6
    - rpds-py==0.30.0
    - safetensors==0.7.0
    - scipy==1.15.3
    - seaborn==0.13.2
    - sentencepiece==0.2.0
    - sentry-sdk==2.48.0
    - setproctitle==1.3.7
    - setuptools==80.9.0
    - shellingham==1.5.4
    - six==1.17.0
    - sse-starlette==3.0.4
    - starlette==0.50.0
    - supervisor==4.3.0
    - sympy==1.14.0
    - tabulate==0.9.0
    - tokenizers==0.22.1
    - torch==2.4.0
    - torchaudio==2.9.0
    - torchvision==0.19.0
    - transformers==4.57.3
    - triton==3.0.0
    - typer==0.20.1
    - typer-slim==0.20.1
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - uvicorn==0.40.0
    - uvloop==0.22.1
    - vllm==0.6.3
    - watchfiles==1.1.1
    - websockets==15.0.1
    - wheel==0.45.1
    - xformers==0.0.27.post2
    - xgrammar==0.1.27
    - zipp==3.23.0
prefix: /YOUR_PATH/conda_envs/collusive_agent
